services:
  angular-app:
    image: angular-app:latest
    ports:
      - "80:80"
    restart: always

  build:
    image: angular-build
    build:
      context: .
      dockerfile: Dockerfile.build

  test:
    image: angular-test
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - build
